### ISSUE TITLE
Работает не на всех страницах

### ISSUE THREAD

**Issue by Semigradsky** [WebDevArchive/VK-CodeSyntaxHighlighter#3]
На стене паблика:
![image](https://cloud.githubusercontent.com/assets/1198848/8383000/940d5c56-1c3f-11e5-80e0-43e2a5833d63.png)

но https://vk.com/wall-66170841_25500?reply=25505
![image](https://cloud.githubusercontent.com/assets/1198848/8383004/9cf63130-1c3f-11e5-84ee-4a9f0118588d.png)

**Comment by Stas404** [comment]
Поймал. 
Надо запустить `searchLoop()` по элементам с классом `fw_reply_text`, чтобы «наблюдатель» также обрабатывал и комментарии на страницах с отдельными постами.
Решается буквально одной строчкой в функции «highlightCallback» в [index.js](https://github.com/WebDevArchive/VK-CodeSyntaxHighlighter/blob/master/files/index.js#L37):

``` javascript
searchLoop('fw_reply_text');
```

В следующий релиз обязательно включу, спасибо.
